# Generated by Django 3.0.8 on 2020-09-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idE', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
                'db_table': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('matriculaMP', models.IntegerField(default=0, verbose_name='Matrícula Provincial')),
                ('matriculaME', models.IntegerField(blank=True, null=True, verbose_name='Matrícula Especialidad')),
                ('cuit', models.CharField(help_text='Ej:11-12345678-0', max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('trabaja_en', models.CharField(choices=[('CP', 'consultorio propio'), ('CM', 'centro médico')], default='', max_length=2)),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('domicilio', models.CharField(max_length=30)),
                ('email', models.EmailField(help_text='Ej: hola@ejemplo.com', max_length=30, verbose_name='E-mail')),
                ('convenioOSECAC', models.CharField(choices=[('S', 'Con Convenio'), ('N', 'Sin Convenio')], max_length=1)),
                ('especialidad', models.ManyToManyField(to='doctores.Especialidad')),
            ],
            options={
                'verbose_name_plural': 'Doctores',
                'db_table': 'Doctores',
            },
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(fields=('matriculaMP', 'matriculaME'), name='matricula'),
        ),
    ]
