# Generated by Django 3.0.8 on 2020-08-16 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('matriculaDoc', models.IntegerField(verbose_name='Matrícula')),
                ('cuit', models.CharField(help_text='Ej:11-12345678-0', max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('domicilio', models.CharField(max_length=30)),
                ('email', models.EmailField(help_text='Ej: hola@ejemplo.com', max_length=30, verbose_name='E-mail')),
                ('convenioOSECAC', models.CharField(choices=[('S', 'Con Convenio'), ('N', 'Sin Convenio')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idEspecialidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorTieneEspecialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=250)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.Doctor')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.Especialidad')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidad',
            field=models.ManyToManyField(through='doctores.DoctorTieneEspecialidad', to='doctores.Especialidad'),
        ),
    ]
