# Generated by Django 3.0.8 on 2020-09-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='domicilio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, help_text='Ej: hola@ejemplo.com', max_length=30, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='matriculaMP',
            field=models.IntegerField(verbose_name='Matrícula Provincial'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='trabaja_en',
            field=models.CharField(choices=[('CP', 'consultorio propio'), ('CM', 'centro médico')], max_length=2),
        ),
    ]
