# Generated by Django 3.0.8 on 2020-08-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name_plural': 'Doctores'},
        ),
        migrations.AlterModelOptions(
            name='doctortieneespecialidad',
            options={'verbose_name_plural': 'Doctor tiene Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name_plural': 'Especialidades'},
        ),
    ]
