# Generated by Django 3.0.8 on 2020-09-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0002_auto_20200905_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-apellidos'], 'verbose_name_plural': 'Doctores'},
        ),
    ]
