# Generated by Django 3.0.8 on 2020-09-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctores', '0001_initial'),
        ('localidad_atencion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=150)),
                ('domicilio', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('horario', models.TextField(default='', max_length=200)),
                ('e_mail', models.EmailField(max_length=150)),
                ('doctores', models.ManyToManyField(to='doctores.Doctor')),
                ('especialidades', models.ManyToManyField(to='doctores.Especialidad')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidad_atencion.Localidad')),
            ],
            options={
                'verbose_name_plural': 'Centros médicos',
                'db_table': 'Centros medicos',
            },
        ),
    ]
