# Generated by Django 3.0.4 on 2020-10-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
        ('centromedico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centromedico',
            name='doctores',
            field=models.ManyToManyField(blank=True, null=True, to='doctores.Doctor'),
        ),
    ]
