# Generated by Django 3.0.8 on 2020-09-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0002_auto_20200905_1250'),
        ('centromedico', '0002_auto_20200905_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centromedico',
            options={'ordering': ['-razonSocial'], 'verbose_name_plural': 'Centros médicos'},
        ),
        migrations.AlterField(
            model_name='centromedico',
            name='doctores',
            field=models.ManyToManyField(blank=True, null=True, to='doctores.Doctor'),
        ),
    ]
