# Generated by Django 3.0.8 on 2020-08-16 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidad_atencion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('tipoDNI', models.CharField(choices=[('1', 'DNI'), ('2', 'LC'), ('3', 'LE'), ('4', 'S/D')], max_length=1)),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=30)),
                ('afiliado', models.CharField(choices=[('S', 'AFILIADO'), ('N', 'NO AFILIADO')], max_length=1)),
                ('nroAfiliado', models.IntegerField(blank=True, null=True, verbose_name='N° Afiliado')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidad_atencion.Localidad')),
            ],
            options={
                'unique_together': {('tipoDNI', 'dni')},
            },
        ),
    ]
