# Generated by Django 3.0.8 on 2020-09-10 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidad_atencion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDNI', models.CharField(choices=[('DNI', 'DNI'), ('LC', 'LC'), ('LE', 'LE'), ('S/D', 'S/D')], max_length=3)),
                ('dni', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=30)),
                ('afiliado', models.CharField(choices=[('S', 'AFILIADO'), ('N', 'NO AFILIADO')], max_length=1)),
                ('nroAfiliado', models.IntegerField(blank=True, null=True, verbose_name='N° Afiliado')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidad_atencion.Localidad')),
            ],
            options={
                'verbose_name_plural': 'Beneficiarios',
                'db_table': 'Beneficiarios',
                'ordering': ['-apellidos'],
            },
        ),
        migrations.AddConstraint(
            model_name='beneficiario',
            constraint=models.UniqueConstraint(fields=('tipoDNI', 'dni'), name='documento'),
        ),
    ]
