# Generated by Django 3.0.8 on 2020-08-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiario',
            options={'verbose_name_plural': 'Beneficiarios'},
        ),
    ]
