# Generated by Django 3.0.8 on 2020-09-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido_ambulatorio', '0001_initial'),
        ('beneficiario', '0001_initial'),
        ('doctores', '0001_initial'),
        ('centromedico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('dias_dados', models.IntegerField(blank=True, null=True)),
                ('dias_prorroga', models.IntegerField(blank=True, null=True)),
                ('tipo1_internacion', models.CharField(choices=[('PISO', 'PISO'), ('TERAPIA', 'TERAPIA'), ('NEO', 'NEO')], max_length=10)),
                ('tipo2_internacion', models.CharField(choices=[('CLINICO', 'CLINICO'), ('QUIRURGICO', 'QUIRURGICO')], max_length=10)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Beneficiario')),
                ('centromedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centromedico.CentroMedico')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido_ambulatorio.Diagnostico')),
                ('doctorTratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.Doctor')),
            ],
            options={
                'verbose_name_plural': 'Internaciones',
                'db_table': 'Internación',
            },
        ),
    ]
