# Generated by Django 3.0.8 on 2020-08-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_internacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internacion',
            name='dias_dados',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='internacion',
            name='dias_prorroga',
            field=models.IntegerField(null=True),
        ),
    ]
