# Generated by Django 3.0.8 on 2020-09-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_internacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='internacion',
            table='Internacion',
        ),
    ]
