# Generated by Django 3.0.8 on 2020-09-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_internacion', '0002_auto_20200831_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internacion',
            name='dias_dados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internacion',
            name='dias_prorroga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internacion',
            name='fecha_egreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
