# Generated by Django 3.0.8 on 2020-09-10 22:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centromedico', '0001_initial'),
        ('beneficiario', '0001_initial'),
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('codigoCirugia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_Cirugia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(default=datetime.datetime.now)),
                ('estado_clave', models.CharField(choices=[('P', 'PENDIENTE'), ('R', 'RECHAZADA'), ('A', 'AUTORIZADA')], max_length=1)),
                ('material', models.BooleanField()),
                ('prequirgicos', models.BooleanField()),
                ('fecha_cirugia', models.DateField(blank=True, null=True)),
                ('tipo_cirugia', models.CharField(choices=[('P', 'PROGRAMADA'), ('U', 'URGENCIA')], max_length=1)),
                ('importe_coseguro', models.FloatField(blank=True)),
                ('observaciones', models.TextField(max_length=200)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Beneficiario')),
                ('centromedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centromedico.CentroMedico')),
                ('cirugia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud_cirugia.Cirugia')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.Doctor')),
            ],
            options={
                'verbose_name_plural': 'Solicitud_de_cirugias',
                'db_table': 'Solicitud_cirugia',
            },
        ),
    ]
