# Generated by Django 3.0.4 on 2020-10-07 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_cirugia', '0002_auto_20200910_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud_cirugia',
            old_name='prequirgicos',
            new_name='prequirurgicos',
        ),
    ]
