# Generated by Django 3.0.8 on 2020-08-16 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidad_atencion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroMedico',
            fields=[
                ('cuitCM', models.CharField(help_text='Ej:12-34567890-0', max_length=13, primary_key=True, serialize=False)),
                ('razonSocial', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('horario', models.TextField(max_length=200)),
                ('e_mail', models.EmailField(max_length=50)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidad_atencion.Localidad')),
            ],
        ),
    ]
