# Generated by Django 3.0.8 on 2020-08-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro_medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centromedico',
            options={'verbose_name_plural': 'Centros médicos'},
        ),
    ]
