# Generated by Django 3.0.8 on 2020-08-17 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro_medico', '0002_auto_20200816_1915'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='centromedico',
            table='Centros médicos',
        ),
    ]
