# Generated by Django 3.0.8 on 2020-08-17 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0003_auto_20200816_2203'),
        ('centro_medico', '0003_auto_20200816_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroMedico_brinda_Especialidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centroMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro_medico.CentroMedico')),
                ('especialidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.Especialidad')),
            ],
            options={
                'verbose_name_plural': 'Centros Médicos brinda Especialidades',
                'db_table': 'CM_brinda_Especialidades',
            },
        ),
    ]
