# Generated by Django 3.0.8 on 2020-08-16 20:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiario', '0001_initial'),
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_Diagnostico', models.CharField(max_length=4)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Practica_Medica',
            fields=[
                ('codigo_Practica', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Ambulatorio',
            fields=[
                ('idPedido', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(default=datetime.datetime.now)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='PA_tiene_Practicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prescripcion', models.DateField()),
                ('autorizado', models.CharField(choices=[('P', 'PENDIENTE'), ('R', 'RECHAZADO'), ('A', 'AUTORIZADO')], max_length=1)),
                ('importeCoseguro', models.FloatField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=200, null=True)),
                ('diagnosticos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido_ambulatorio.Diagnostico')),
                ('doctores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.Doctor')),
                ('practicas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido_ambulatorio.Practica_Medica')),
            ],
        ),
    ]
