# Generated by Django 3.0.8 on 2020-09-10 22:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiario', '0001_initial'),
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.TextField(default=' ', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Diagnósticos',
                'db_table': 'Diagnostico',
            },
        ),
        migrations.CreateModel(
            name='Practica_Medica',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Práctica médica',
                'verbose_name_plural': 'Prácticas médicas',
                'db_table': 'PracticasMedicas',
            },
        ),
        migrations.CreateModel(
            name='Pedido_Ambulatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPedido', models.IntegerField()),
                ('fecha_ingreso', models.DateField(default=datetime.datetime.now)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Beneficiario')),
            ],
            options={
                'verbose_name_plural': 'Pedidos ambulatorios',
                'db_table': 'PedidosAmbulatorios',
            },
        ),
        migrations.CreateModel(
            name='Detalle_PedidoMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizado', models.CharField(choices=[('P', 'PENDIENTE'), ('R', 'RECHAZADO'), ('A', 'AUTORIZADO')], max_length=1)),
                ('importeCoseguro', models.FloatField(blank=True, null=True, verbose_name='Importe Coseguro')),
                ('observaciones', models.TextField(blank=True, max_length=300, null=True)),
                ('doctores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.Doctor')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido_ambulatorio.Pedido_Ambulatorio')),
                ('practicas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido_ambulatorio.Practica_Medica')),
            ],
            options={
                'verbose_name_plural': 'Detalles',
                'db_table': 'DetallePedidoMedico',
            },
        ),
    ]
