# Generated by Django 3.0.8 on 2020-09-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.TextField(default=' ', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Diagnósticos',
                'db_table': 'Diagnostico',
            },
        ),
        migrations.CreateModel(
            name='Practica_Medica',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Práctica médica',
                'verbose_name_plural': 'Prácticas médicas',
                'db_table': 'PracticasMedicas',
            },
        ),
    ]
