# Generated by Django 3.0.8 on 2020-09-06 00:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0003_auto_20200905_1647'),
        ('beneficiario', '0002_auto_20200905_1633'),
        ('pedido_ambulatorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_Ambulatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPedido', models.IntegerField(default=None)),
                ('fecha_ingreso', models.DateField(default=datetime.datetime.now)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Beneficiario')),
            ],
            options={
                'verbose_name_plural': 'Pedidos ambulatorios',
                'db_table': 'PedidosAmbulatorios',
            },
        ),
        migrations.CreateModel(
            name='Detalle_PedidoMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prescripcion', models.DateField()),
                ('autorizado', models.CharField(choices=[('P', 'PENDIENTE'), ('R', 'RECHAZADO'), ('A', 'AUTORIZADO')], max_length=1)),
                ('importeCoseguro', models.FloatField(blank=True, null=True, verbose_name='Importe Coseguro')),
                ('diagnosticos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido_ambulatorio.Diagnostico')),
                ('doctores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.Doctor')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido_ambulatorio.Pedido_Ambulatorio')),
                ('practicas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido_ambulatorio.Practica_Medica')),
            ],
            options={
                'verbose_name_plural': 'Detalles',
                'db_table': 'Detalle_PedidoMedico',
            },
        ),
    ]
