# Generated by Django 3.0.8 on 2020-08-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_ambulatorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostico',
            options={'verbose_name_plural': 'Diagnósticos'},
        ),
        migrations.AlterModelOptions(
            name='pa_tiene_practicas',
            options={'verbose_name': 'Prácticas del Pedido médico', 'verbose_name_plural': 'Prácticas del Pedido médico'},
        ),
        migrations.AlterModelOptions(
            name='pedido_ambulatorio',
            options={'verbose_name_plural': 'Pedidos ambulatorios'},
        ),
        migrations.AlterModelOptions(
            name='practica_medica',
            options={'verbose_name': 'Práctica médica', 'verbose_name_plural': 'Prácticas médicas'},
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='nombre',
            field=models.CharField(default='hola', max_length=50),
        ),
        migrations.AlterModelTable(
            name='diagnostico',
            table='Diagnostico',
        ),
    ]
