# Generated by Django 3.0.8 on 2020-09-06 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0002_auto_20200905_1633'),
        ('doctores', '0003_auto_20200905_1647'),
        ('pedido_ambulatorio', '0002_detalle_pedidomedico_pedido_ambulatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_pedidomedico',
            name='diagnosticos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido_ambulatorio.Diagnostico'),
        ),
        migrations.AlterField(
            model_name='detalle_pedidomedico',
            name='doctores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctores.Doctor'),
        ),
        migrations.AlterField(
            model_name='detalle_pedidomedico',
            name='fecha_prescripcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_pedidomedico',
            name='practicas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido_ambulatorio.Practica_Medica'),
        ),
        migrations.AlterField(
            model_name='pedido_ambulatorio',
            name='beneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Beneficiario'),
        ),
    ]
