# Generated by Django 3.0.8 on 2020-08-17 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_ambulatorio', '0002_auto_20200816_1915'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pa_tiene_practicas',
            table='PedidoAmbulatorio_tiene_prácticas',
        ),
        migrations.AlterModelTable(
            name='pedido_ambulatorio',
            table='Pedidos Ambulatorios',
        ),
        migrations.AlterModelTable(
            name='practica_medica',
            table='Prácticas médicas',
        ),
    ]
