# Generated by Django 3.0.8 on 2020-08-17 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_ambulatorio', '0003_auto_20200816_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pa_tiene_practicas',
            name='id',
        ),
        migrations.AddField(
            model_name='pa_tiene_practicas',
            name='pedido_ambulatorio_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pedido_ambulatorio.Pedido_Ambulatorio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='codigo_Diagnostico',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedido_ambulatorio',
            name='idPedido',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
