# Generated by Django 3.0.8 on 2020-08-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_ambulatorio', '0004_auto_20200817_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='nombre',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
