# Generated by Django 3.0.8 on 2020-08-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_ambulatorio', '0005_auto_20200817_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='nombre',
            field=models.TextField(default=' ', max_length=250),
        ),
    ]
