# Generated by Django 3.0.8 on 2020-08-17 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_ambulatorio', '0006_auto_20200817_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostico',
            old_name='codigo_Diagnostico',
            new_name='codigo',
        ),
    ]
