# Generated by Django 3.0.8 on 2020-08-17 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_ambulatorio', '0007_auto_20200817_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practica_medica',
            old_name='codigo_Practica',
            new_name='codigo',
        ),
        migrations.RemoveField(
            model_name='practica_medica',
            name='descripcion',
        ),
        migrations.AlterModelTable(
            name='pa_tiene_practicas',
            table='PracticasDelPedido',
        ),
        migrations.AlterModelTable(
            name='pedido_ambulatorio',
            table='PedidosAmbulatorios',
        ),
        migrations.AlterModelTable(
            name='practica_medica',
            table='practicasMedicas',
        ),
    ]
