# Generated by Django 3.0.8 on 2020-08-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_ambulatorio', '0008_auto_20200817_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pa_tiene_practicas',
            name='importeCoseguro',
            field=models.FloatField(blank=True, null=True, verbose_name='Importe Coseguro'),
        ),
        migrations.AlterModelTable(
            name='practica_medica',
            table='PracticasMedicas',
        ),
    ]
